

procesos: markov.x
    ./markov.x
    
markov.x: markov_chain.c
    gcc -fopenmpp markov_chain.c -lm -o markov.x
    
clean:
     rm -f proceso_1 proceso_2 proceso_3 proceso_4 proceso_5 proceso_6 proceso_7 proceso_8 
